name: Sign-in B2C

on:
  push:
    branches: [ master ]
    paths: ['1-Authentication/sign-in-b2c/**', '.github/workflows/**']
  pull_request:
    branches: [ master ]
    paths: ['1-Authentication/sign-in-b2c/**', '.github/workflows/**']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      relativePath: ./1-Authentication/sign-in-b2c

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        working-directory: ${{ env.relativePath }}
